line-length = 88
exclude = [".env", "migrations"]
fix = true

[format]
quote-style = "single"
docstring-code-format = true

[lint]
select = ["I", "E", "UP", "F"]
fixable = ["ALL"]

[lint.isort]
case-sensitive = true
lines-after-imports = 2
