Table System { 
  ID smallint [pk, unique, not null, increment, note: 'ID da tabela']
  name varchar(6) [unique, not null, note: 'Nome do sistema']
  
  Note: '''
    OE
    SAEC
    PH
    WSOE
    WSSAEC
    ...'''
}

Table Project {
  ID smallint [pk, unique, not null, increment, note: 'ID da tabela']
  name varchar(6) [unique, not null, note: 'Nome do projeto']

  Note: '''
    Financ
    SIPE
    Terras
    ...'''
}

Table PBI {
  ID integer [pk, unique, not null, increment, note: 'ID da tabela']
  number integer [unique, not null, note: 'Número da PBI no VSTS']
  name varchar(128) [unique, not null, note: 'Nome da PBI no VSTS']
  project_id smallint [ref: < Project.ID, not null, note: 'ID do projeto na tabela "Project"']
  feature bool [note: '''
    0 - Deploy
    1 - Sustentação  ''']

  Note: 'Cada PBI de cada Deploy será cadastrada aqui'
}

Table Deploy {
  ID integer [pk, unique, not null, increment, note: 'ID da tabela']
  deploy_date datetime [not null, note: 'Data que ocorreu a deploy']

  Note: 'Cada deploy será cadastrada aqui junto à sua data'
}

Table Status {
  ID smallint [pk, unique, not null, increment, note: 'ID da tabela']
  Status varchar(8) [not null, note:'''
    1 - Aprovada
    2 - Rollback
    3 - Ajuste''']

  Note: 'Determina os status que uma PBI pode assumir em uma Deploy'
}

Table Deploy_PBI {
  ID integer [pk, unique, not null, increment, note: 'ID da tabela']
  deploy_id integer [ref: < Deploy.ID, not null, note: 'ID da deploy na tabela "Deploy"']
  pbi_id integer [ref: < PBI.ID, not null, note: 'ID da PBI na tabela "PBI"']
  status_id smallint [ref: < Status.ID, not null, note: 'ID do resultado na tabela "Status"']
  comment varchar(300) [note: 'Comentário opcional sobre determinada PBI em determinada deploy']

  Note: 'Associa cada Deploy às suas PBIs'
}

Table PBI_System {
  ID integer [pk, unique, not null, increment, note: 'ID da tabela']
  pbi_id integer [ref: <> PBI.ID, not null, note: 'ID da PBI na tabela "PBI"']
  system_id integer [ref:<> System.ID, not null, note: 'ID do sistema na tabela "System"']

  Note: 'Associa PBIs e sistemas'
}
